### ISSUE TITLE
pfn 0 print in all cases

### ISSUE THREAD

**Issue by sarabjeetsingh007** [dwks/pagemap#2]
I am running it on x86_64 Linux.
Every Pid I run gives me all physical addresses as 0:
: pfn 0

**Comment by ho28** [comment]
From the kernel documentation:
"Since Linux 4.0 only users with the CAP_SYS_ADMIN capability can get PFNs.
   In 4.0 and 4.1 opens by unprivileged fail with -EPERM.  Starting from
   4.2 the PFN field is zeroed if the user does not have CAP_SYS_ADMIN.
   Reason: information about PFNs helps in exploiting Rowhammer vulnerability."

You need sudo access
